### ISSUE TITLE
BLURB for EVENTS: Text needed for Investigator Meetings

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#110]

**Comment by jenniferbrickwell** [comment]
Investigator Meetings
We have experience in Phase I-IV of clinical trial development and understand the importance of successful Investigator meetings in order to facilitate the process of bringing a drug to market. We ensure that our Investigator Meetings are both engaging, relevant and interactive to ensure that key information is disseminated in a clear way.
