### ISSUE TITLE
Minor amendments

### ISSUE THREAD

**Issue by jenniferbrickwell** [stereocats/jenniferbrickwell#147]
1. Conferences
Can we reorder- Pharma, Conferences, IM, Academic

2. IM- Investigator Meeting (caps)
3. Academic- can we replace in last sentence 'event' with conference
4. Community Event 'to ensure that it is successful' can we replace 'it ' with 'your event'
  Can we make special discount singular
5. Home Page
Please amend last sentence to read- We specialise in delivering high quality events at ...etc.
Please then add We specialise in 3 key areas of service- Events, Conferences and Training.

6. Can we add Home Page to the title bar

**Comment by iandstanley** [comment]
Will change ASAP. 

Busy with last minute prep today 

Hopefully get chance to sort out tomorrow at some point 

On 25 Jul 2016, at 12:13, Jennifer Brickwell <notifications@github.com> wrote:

Conferences
Can we reorder- Pharma, Conferences, IM, Academic

IM- Investigator Meeting (caps)

Academic- can we replace in last sentence 'event' with conference
Community Event 'to ensure that it is successful' can we replace 'it ' with 'your event' Can we make special discount singular
Home Page
Please amend last sentence to read- We specialise in delivering high quality events at ...etc.
Please then add We specialise in 3 key areas of service- Events, Conferences and Training.

Can we add Home Page to the title bar

**Comment by iandstanley** [comment]
completed the following

- [X] Can we reorder- Pharma, Conferences, IM, Academic

- [X] IM- Investigator Meeting (caps)

- [X] Academic- can we replace in last sentence 'event' with conference

- [X] Community Event 'to ensure that it is successful' can we replace 'it ' with 'your event' Can we make special discount singular

- [X] Please amend last sentence to read- We specialise in delivering high quality events at ...etc.

- [X] Please then add We specialise in 3 key areas of service- Events, Conferences and Training.

**Comment by iandstanley** [comment]
With regards to the home page being in the menu 

- Most websites these days the website name, company name or logo links to the home page and most people have come to expect that behaviour – as such many designs do not list the home page
- Because of the length of the company name adding home to the menu would cause one of the two problems:


1. The title bar would be too crowded and be discomforting / disconcerting to read for many viewers
2. The text of the company name and menu items would have to be reduced to keep sufficient white space making it difficult for some to read

Having said that ...

On Narrower screens where I will be switching to a mobile -style menu (yet to be finished coding) the home page will be listed
